name: Node.js CI

on:
  push:
    brannches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # install & build npm
      - name: Use Node.js
        uses: actions/checkout@v3
        uses: actions/setup-node@v3
        with:
          node-version: '12.16.1'
      - run: npm ci
      - run: npm run build

      # build docker
      - name: Build Container
        uses: actions/checkout@v3
        uses: docker/build-push-action@v2
        with:
          username: edanpiro
          password: ${{ secrets.API_TOKEN }}
          registry: docker.pkg.github.com
          repository: edanpiro/demo-html
          tag_with_sha: true
